name: Release

on:
  workflow_dispatch:
  repository_dispatch:

jobs:

  build_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.10.0
      with:
        mirror: 'http://mirrors.ocf.berkeley.edu/qt/'

    - name: do build
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        cd src
        release_win.bat
    
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Upload
      run: |
        pip install -r requirements.txt
        python upload.py
      env: 
        filename: 'windows.zip'
        nutstore_url: ${{ secrets.NUTSTORE_URL }}
        nutstore_username: ${{ secrets.NUTSTORE_USERNAME }}
        nutstore_password: ${{ secrets.NUTSTORE_PASSWORD }}
